### ISSUE TITLE
replit

### ISSUE THREAD

**Issue by mw985793** [Sebastian09-09/snicord#4]
ok so i followed all steps of setting snicord bronze on replit but when i run the code it gives this error 
Traceback (most recent call last):
  File "/home/runner/snicord/.pythonlibs/lib/python3.10/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/nix/store/xf54733x4chbawkh1qvy9i1i4mlscy1c-python3-3.10.11/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/nix/store/xf54733x4chbawkh1qvy9i1i4mlscy1c-python3-3.10.11/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/nix/store/xf54733x4chbawkh1qvy9i1i4mlscy1c-python3-3.10.11/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/snicord/main.py", line 125, in <module>
    run(TOKEN)
  File "/home/runner/snicord/main.py", line 120, in run
    sb = Selfbot(token)
  File "/home/runner/snicord/main.py", line 31, in __init__
    self.user = self.getUserData(self.homeChannel)
  File "/home/runner/snicord/main.py", line 80, in getUserData
    return r.json()["author"] 
  File "/home/runner/snicord/.pythonlibs/lib/python3.10/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by Sebastian09-09** [comment]
are you logging out of the account after entering your token ?

**Comment by SANKETOP** [comment]
> are you logging out of the account after entering your token ?

I am also facing same problem and not even logging out the accounts

**Comment by mw985793** [comment]
> are you logging out of the account after entering your token ?

no

**Comment by Sebastian09-09** [comment]
guy follow the setup i have added in README.md file 
its working fine
